on:
  release:
    types:
      - published
      - edited
jobs:
  gh-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref_type == 'branch' }}
        run: echo "whatsup"
      - name: Always
        run: echo "always"